"""add run table indexes and constraints

Revision ID: 7f7304112143
Revises: c14d7c0be434
Create Date: 2026-09-23 10:18:57.683641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f7304112143'
down_revision: Union[str, Sequence[str], None] = 'c14d7c0be434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_plan_steps_run_id'), 'plan_steps', ['run_id'], unique=False)
    op.create_unique_constraint('uq_plan_steps_run_order', 'plan_steps', ['run_id', 'step_order'])
    op.create_index('ix_research_runs_status_created_at', 'research_runs', ['status', 'created_at'], unique=False)
    op.create_index('ix_run_events_run_id_ts', 'run_events', ['run_id', 'ts'], unique=False)
    op.create_index(op.f('ix_sources_run_id'), 'sources', ['run_id'], unique=False)
    op.create_index(op.f('ix_subagent_tasks_plan_step_id'), 'subagent_tasks', ['plan_step_id'], unique=False)
    op.create_index(op.f('ix_subagent_tasks_run_id'), 'subagent_tasks', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subagent_tasks_run_id'), table_name='subagent_tasks')
    op.drop_index(op.f('ix_subagent_tasks_plan_step_id'), table_name='subagent_tasks')
    op.drop_index(op.f('ix_sources_run_id'), table_name='sources')
    op.drop_index('ix_run_events_run_id_ts', table_name='run_events')
    op.drop_index('ix_research_runs_status_created_at', table_name='research_runs')
    op.drop_constraint('uq_plan_steps_run_order', 'plan_steps', type_='unique')
    op.drop_index(op.f('ix_plan_steps_run_id'), table_name='plan_steps')
    # ### end Alembic commands ###
